{% set name = "types-mypy-extensions" %}
{% set version = "1.0.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-mypy-extensions-{{ version }}.tar.gz
  sha256: 902775bd232170736a7827d8b09c5a4f1bd85230d71bea65994753fc98e80903

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/mypy_extensions-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for mypy-extensions
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
