{% set name = "types-mypy-extensions" %}
{% set version = "1.0.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-mypy-extensions-{{ version }}.tar.gz
  sha256: f3470292a326b0675e4999bd866555f3e456b071b2e5c1d28fbd2d6a1f780378

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/mypy_extensions-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for mypy-extensions
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
